#pragma once

#include <stdint.h>
#include <vector>
#include <windows.h>
#include <string>
#include <iostream>
#include <Shlobj.h>
#include <set>
#include <algorithm>
#include <memory>
#include <functional>
#include <cmath>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <intrin.h>
#include <detours.h>
#include <Wincrypt.h>
#include <TlHelp32.h>
#include <Dbghelp.h>
#include <atomic>
#include <assert.h>
#include <array>
#include <ctime>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <queue>
#include <sstream>
#include <VersionHelpers.h>
#include <fstream>